GO
CREATE DATABASE FinalProject
GO
USE FinalProject
GO
CREATE TABLE Person
(
	id INT NOT NULL,
	Cedula VARCHAR(50) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Celular VARCHAR(50) NOT NULL,
	Direccion VARCHAR(200) NOT NULL,
)
GO
SELECT * FROM Person
